obj-$(CONFIG_SERIAL_NUM_ROSY)		+= serial_num.o
obj-$(CONFIG_SECBOOT_FUSE_ROSY)	    += secboot_fuse.o
obj-$(CONFIG_CPUMAXFREQ_ROSY)		+= cpumaxfreq.o
obj-$(CONFIG_BOOT_INFO_ROSY)		+= bootinfo.o
obj-$(CONFIG_HARDWARE_INFO_ROSY)	+= hardware_info.o